//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisSaltesa.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Clientes_Trans
    {
       
        public Clientes_Trans()
        {
            this.Facturas_Trans = new HashSet<Facturas_Trans>();
            

        }
        [Key]
        [Column(Order = 1)]
        public int Cliente_id { get; set; }
        public string Cliente_Nombre { get; set; }
        public string Cliente_Apellido { get; set; }
        public string Cliente_Direccion { get; set; }
        public string Cliente_Email { get; set; }
        public string Cliente_Telefono { get; set; }
        public string Cliente_Celular { get; set; }
        public string Cliente_RNC { get; set; }
        [NotMapped]
        public int Marca_id { get; set; }
        [NotMapped]
        public int Modelo_id { get; set; }
        [NotMapped]
        public Int32? Cantidad_Registros { get; set; }
        [NotMapped]
        public Int32? Ultima_Linea { get; set; }
        [NotMapped]
        public Int32? Linea { get; set; }
        [NotMapped]
        public bool Registro_Estado { get; set; }
        [NotMapped]
        public string Registro_Usuario { get; set; }
        [NotMapped]
        public Nullable<System.DateTime> Registro_Fecha { get; set; }
   
        public virtual ICollection<Facturas_Trans> Facturas_Trans { get; set; }
       


    }
}
