//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisSaltesa.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Comprobantes_Cata
    {
      
        public Comprobantes_Cata()
        {
            //this.Tipo_Comprobantes_Trans = new HashSet<Tipo_Comprobantes_Trans>();
        }

        [Key]
        [Column(Order = 1)]
        public byte Comprobante_id { get; set; }
        public string Comprobante_Nombre { get; set; }
        public string Comprobante_Descripcion { get; set; }
        // public bool Registro_Estado { get; set; }
        // public string Regidtro_Usuario { get; set; }
        //public System.DateTime Registro_Fecha { get; set; }
    
        //public virtual ICollection<Tipo_Comprobantes_Trans> Tipo_Comprobantes_Trans { get; set; }
    }
}
