//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisSaltesa.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Empleados_Trans")]
    public partial class Empleados_Trans
    {
        [Key]
        [Column(Order = 1)]
        public Int32 Empleado_id { get; set; }
        public string Empleado_Nombre { get; set; }
        public string Empleado_Apellido { get; set; }
        public string Empleado_Nombre_Completo { get; set; }
        public string Empleado_Direccion { get; set; }
        public string Empleado_Telefono { get; set; }
        public string Empleado_Celular { get; set; }
        public int Empresa_ID { get; set; }
        public Nullable<byte> Empleado_Edad { get; set; }
        public bool Registro_Estado { get; set; }
        public string Registro_Usuario { get; set; }
        public System.DateTime Registro_Fecha { get; set; }
    
        public virtual Empresas_Trans Empresas_Trans { get; set; }
    }
}
