//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisSaltesa.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Empresas_Trans
    {
       
        public Empresas_Trans()
        {
            this.Empleados_Trans = new HashSet<Empleados_Trans>();
            this.Tipo_Comprobantes_Trans = new HashSet<Tipo_Comprobantes_Trans>();
        }

        [Key]
        [Column(Order = 1)]
        public int Empresa_id { get; set; }
        public string Empresa_User { get; set; }
        public string Empresa_Password { get; set; }
        public string Empresa_Nombre { get; set; }
        public string Empresa_Email { get; set; }
        public string Empresa_Direccion { get; set; }
        public string Empresa_Telefono { get; set; }
        public string Empresa_Logo { get; set; }
        public bool Registro_Estado { get; set; }
        public string Registro_Usuario { get; set; }
        public System.DateTime Registro_Fecha { get; set; }
    
        public virtual ICollection<Empleados_Trans> Empleados_Trans { get; set; }

        public virtual ICollection<Tipo_Comprobantes_Trans> Tipo_Comprobantes_Trans { get; set; }
    }
}
