//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisSaltesa.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Facturas_Trans
    {
        [Key]
        [Column(Order = 1)]
        public int factura_id { get; set; }
        public int Cliente_ID { get; set; }
        public int Marca_ID { get; set; }
        public int Modelo_ID { get; set; }
        public byte TipoVehiculo_ID { get; set; }
        public string Factura_Comprobante { get; set; }
        public byte TipoTransaccion_ID { get; set; }
        public string Factura_NCF { get; set; }
        public string Factura_NIF { get; set; }
        public decimal Factura_ITBIS { get; set; }
        public decimal Factura_Neto { get; set; }
        public decimal Factura_Subtotal { get; set; }
        public decimal Factura_Total { get; set; }
        public bool Registro_Estado { get; set; }
        public string Registro_Usuario { get; set; }
        public Nullable<System.DateTime> Registro_Fecha { get; set; }
        public virtual Clientes_Trans Clientes_Trans { get; set; }
        public virtual Marcas_Cata Marcas_Cata { get; set; }
        public virtual Modelos_Cata Modelos_Cata { get; set; }
        public virtual Tipo_Transaccion_Cata Tipo_Transaccion_Cata { get; set; }
        public virtual Tipo_Vehiculo_Cata Tipo_Vehiculo_Cata { get; set; }

    }
}
