//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisSaltesa.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Inventarios_Trans
    {

        [Key]
        [Column(Order = 1)]
        public int Inventario_id { get; set; }
        public int Producto_ID { get; set; }
        public int Categoria_ID { get; set; }
        public int Proveedor_ID { get; set; }
        public int Inventario_Entrada { get; set; }
        public int Inventario_Stock { get; set; }
        public int Inventario_Salida { get; set; }
        public bool Registro_Estado { get; set; }
        public string Registro_Usuario { get; set; }
        public System.DateTime Registro_Fecha { get; set; }
    }
}
